server:
  forward-headers-strategy: framework
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gmp
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 30MB
      file-size-threshold: 3KB
      max-file-size: 30MB
#------------------Security Specific Properties-------
app:
  secret-key: J@!gt*K
  oauth2-redirect: https://mismart.vercel.app/login-success
  detection:
    url:
      detect: http://localhost:5000/check-face
      create: http://localhost:5000/post-face
beholder:
  app:
    jwtSecret:
      bezKoderSecretKey
    jwtExpirationMs:
      86400000


logging:
  file:
    path: /logs
    name: /logs/application.log

detection:
  recogize-url: http://localhost:5000/check-face
  create-url: http://localhost:5000/post-face




