server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
spring:
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1062517910184-tkrs8onebj1p401sb2qvao7an4pvrq23.apps.googleusercontent.com
            client-secret: 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

  config:
    import: optional:file:.env[.properties]
  messages:
    always-use-message-format: false
    basename: i18n/messages_vi
    encoding: UTF-8
    use-code-as-default-message: false
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: thanhhuyne113@gmail.com
    password: drzltompxzhpoffe
    port: '587'

# Config OAuth2
#app:
#  firebase-configuration-file: /store/vuondau-450bf-firebase-adminsdk-al83z-5d94e1225d.json
#  secret-key: J@!gt*K
#  oauth2:
#    authorizedRedirectUris: http://localhost:8081/oauth2/redirect,myandroidapp://oauth2/redirect,myiosapp://oauth2/redirect,http://localhost:3000/login,http://localhost:3000/login,https://mismart.vercel.app/login-success
#

# Return URL after payment
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# VNPay Config
vnp_product_type: 250000
vnp_PayUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp_HashSecret: NJJDAQCFVUBSYMOUNBJUZJQSXDEWEPKY
vnp_Returnurl: http://localhost:8082/api/transactions/pay/vnpay/result
vnp_TmnCode: 2P0JI5DH
vnp_apiUrl: https://sandbox.vnpayment.vn/merchant_webapi/merchant.html

# External API
provinces: https://provinces.open-api.vn/api/?depth=1

bank:
  url: https://api.vietqr.io/v2/banks

#------------------Security Specific Properties-------
beholder:
  app:
    jwtSecret:
      bezKoderSecretKey
    jwtExpirationMs:
      86400000
  #------------------MinIO DEV---------------#
minio:
  access:
    key: Ed9hULk92IyS2Glb
    secret: GVk3tHgV3x6tiCR158V0RyFxOFH5IM5O
  url: https://mismart.online
  bucket:
    name: bsmart
  endpoint: https://mismart.online

icon:
  success: http://103.173.155.221:9000/bsmart/checked.png
  fail: http://103.173.155.221:9000/bsmart/fail.png

host:
  url: https://mismart.vercel.app/confirm_email/

forgot-password:
  url: https://mismart.vercel.app/forgot_password/





